FROM --platform=linux/amd64 starmetal/fuxa:latest as builder

FROM node:18
RUN apt-get update && apt-get install -y sqlite3 libsqlite3-dev fswebcam && \
    apt-get autoremove -yqq --purge && \
    apt-get clean  && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /fuxa/server /fuxa/server
COPY --from=builder /fuxa/client/dist /fuxa/client/dist

WORKDIR /fuxa/server
# reinstall sqlite3 for multi platform
RUN rm -rf node_modules/sqlite3 && npm install --build-from-source --sqlite=/usr/bin sqlite3
# reinstall epoll for multi platform
RUN rm -rf node_modules/epoll && npm install epoll
EXPOSE 1881
ENTRYPOINT [ "npm", "start" ]
