FROM starmetal/fuxa:latest as builder

FROM node:18
RUN apt-get update && apt-get install -y sqlite3 libsqlite3-dev && \
    apt-get autoremove -yqq --purge && \
    apt-get clean  && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /fuxa/server /fuxa/server
COPY --from=builder /fuxa/client/dist /fuxa/client/dist

WORKDIR /fuxa/server
EXPOSE 1881
ENTRYPOINT [ "npm", "start" ]
