FROM node:18-bookworm as builder
ARG NODE_SNAP=false
ARG USE_ODBC=false

# Workaround for sqlite3 https://stackoverflow.com/questions/71894884/sqlite3-err-dlopen-failed-version-glibc-2-29-not-found
RUN apt-get update && apt-get install -y sqlite3 libsqlite3-dev

WORKDIR /fuxa
ADD . /fuxa/
WORKDIR /fuxa/client
RUN npm install --legacy-peer-deps && npm run build -- -c production

WORKDIR /fuxa/server
RUN npm install --legacy-peer-deps

# Install options snap7
RUN if [ "$NODE_SNAP" = "true" ]; then \
    npm install node-snap7; \
    fi

RUN if [ "$USE_ODBC" = "true" ]; then \
    npm i odbc; \
    fi

FROM node:18-bookworm
ARG USE_ODBC=false

COPY --from=builder /fuxa/server /fuxa/server
COPY --from=builder /fuxa/client/dist /fuxa/client/dist

WORKDIR /fuxa/server

RUN if [ "$USE_ODBC" = "true" ]; then \
    apt-get update && apt-get install -y dos2unix; \
    apt-get install -y build-essential unixodbc unixodbc-dev; \
    dos2unix ../odbc/install_odbc_drivers.sh && chmod +x ../odbc/install_odbc_drivers.sh; \
    cd ../odbc && ./install_odbc_drivers.sh; \
    cp ../odbc/odbcinst.ini /etc/odbcinst.ini; \
    fi

RUN apt-get update && apt-get install -y sqlite3 libsqlite3-dev && \
     apt-get autoremove -yqq --purge && \
     apt-get clean  && \
     rm -rf /var/lib/apt/lists/*

EXPOSE 1881
ENTRYPOINT [ "npm", "start" ]
